#CUDA_VISIBLE_DEVICES=0 python experiments.py --dataset mnist --arch carlini_cnn --lambda1 0.00005 --lambda2 0.004 --test_lp 1 --solver prox --embedding scattering
#CUDA_VISIBLE_DEVICES=4 python experiments.py --dataset mnist --arch carlini_cnn --lambda1 3.06 --lambda2 0.5  --test_lp inf --solver prox --embedding scattering
#CUDA_VISIBLE_DEVICES=4 python experiments.py --dataset mnist --arch carlini_cnn --lambda1 3.06 --lambda2 0.5  --test_lp inf --solver prox --embedding gan
#CUDA_VISIBLE_DEVICES=4 python experiments.py --dataset mnist --arch carlini_cnn --lambda1 3.06 --lambda2 0.5  --test_lp inf  --solver prox_gan --embedding gan
#CUDA_VISIBLE_DEVICES=4 python experiments.py --dataset cifar --arch densenet --lambda1 3.06 --lambda2 0.5  --test_lp inf --solver prox_gan --embedding gan
#CUDA_VISIBLE_DEVICES=0 python experiments.py --dataset cifar --arch wresnet --lambda1 3.06 --lambda2 0.5  --test_lp inf --solver prox_gan --embedding studiogan
CUDA_VISIBLE_DEVICES=0 python experiments.py --dataset fashionmnist --arch carlini_cnn --lambda2 5.0  --test_lp inf --solver prox_gan --embedding wgan
#CUDA_VISIBLE_DEVICES=4 python experiments.py --dataset mnist --arch carlini_cnn --lambda1 0.999 --lambda2 0.999 --test_lp inf --solver active_refined --embedding scattering
#CUDA_VISIBLE_DEVICES=4 python experiments.py --dataset imagenet --arch alexnet --lambda1 3.06 --lambda2 0.5  --test_lp inf --solver prox_gan --embedding studiogan
#CUDA_VISIBLE_DEVICES=1 python experiments.py --dataset synthetic --arch dense --lambda1 0.99 --lambda2 0.99 --test_lp 1 --solver active_refined --embedding warp
#CUDA_VISIBLE_DEVICES=4 python experiments.py --dataset cifar --arch carlini_cnn --lambda1 0.99 --lambda2 0.99 --test_lp inf --solver prox --embedding scattering
